import { AudioManager } from "../rmmz_managers";

declare class Game_System {
  public _saveEnabled: boolean;
  public _menuEnabled: boolean;
  public _encounterEnabled: boolean;
  public _formationEnabled: boolean;
  public _battleCount: number;
  public _winCount: number;
  public _escapeCount: number;
  public _saveCount: number;
  public _versionId: number;
  public _savefileId: number;
  public _framesOnSave: number;
  public _bgmOnSave: AudioManager.CurrentAudio;
  public _bgsOnSave: AudioManager.CurrentAudio;
  public _windowTone: number[];
  public _battleBgm: AudioManager.CurrentAudio;
  public _victoryMe: AudioManager.CurrentAudio;
  public _defeatMe: AudioManager.CurrentAudio;
  public _savedBgm: AudioManager.CurrentAudio;
  public _walkingBgm: AudioManager.CurrentAudio;

  constructor();
  public initialize(): void;
  public isJapanese(): boolean;
  public isChinese(): boolean;
  public isKorean(): boolean;
  public isCJK(): boolean;
  public isRussian(): boolean;
  public isSideView(): boolean;
  public isAutosaveEnabled(): boolean;
  public isSaveEnabled(): boolean;
  public disableSave(): void;
  public enableSave(): void;
  public isMenuEnabled(): boolean;
  public disableMenu(): void;
  public enableMenu(): void;
  public isEncounterEnabled(): boolean;
  public disableEncounter(): void;
  public enableEncounter(): void;
  public isFormationEnabled(): boolean;
  public disableFormation(): void;
  public enableFormation(): void;
  public battleCount(): number;
  public winCount(): number;
  public escapeCount(): number;
  public saveCount(): number;
  public versionId(): number;
  public savefileId(): number;
  public setSavefileId(savefileId: number): void;
  public windowTone(): number[];
  public setWindowTone(value: number[]): void;
  public battleBgm(): AudioManager.CurrentAudio;
  public setBattleBgm(value: AudioManager.CurrentAudio): void;
  public victoryMe(): AudioManager.CurrentAudio;
  public setVictoryMe(value: AudioManager.CurrentAudio): void;
  public defeatMe(): AudioManager.CurrentAudio;
  public setDefeatMe(value: AudioManager.CurrentAudio): void;
  public onBattleStart(): void;
  public onBattleWin(): void;
  public onBattleEscape(): void;
  public onBeforeSave(): void;
  public onAfterLoad(): void;
  public playTime(): number;
  public playTimeText(): string;
  public saveBgm(): void;
  public replayBgm(): void;
  public saveWalkingBgm(): void;
  public replayWalkingBgm(): void;
  public saveWalkingBgm2(): void;
  public mainFontFace(): string;
  public numberFontFace(): string;
  public mainFontSize(): number;
  public windowPadding(): number;
}

export { Game_System };
